Update patch set 1
Patch Set 1:

Hi David, I think this change makes commands like adb install return a meaningful exit code (thanks!). This happens to break this unit test:

$ cd system/core && python -m unittest -v adb.test_device.ArgumentEscapingTest.test_install_argument_escaping
test_install_argument_escaping (adb.test_device.ArgumentEscapingTest)
Make sure that install argument escaping works. ... ERROR

======================================================================
ERROR: test_install_argument_escaping (adb.test_device.ArgumentEscapingTest)
Make sure that install argument escaping works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "adb/test_device.py", line 271, in test_install_argument_escaping
    self.assertIn("-text;ls;1.apk", self.device.install(tf.name))
  File "adb/device.py", line 304, in install
    return self._simple_call(cmd)
  File "adb/device.py", line 258, in _simple_call
    self.adb_cmd + cmd, stderr=subprocess.STDOUT)
  File "adb/device.py", line 162, in _subprocess_check_output
    return subprocess.check_output(*args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['adb', '-s', '192.168.1.177:6666', 'install', '/tmp/tmp7H7uwB-text;ls;1.apk']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 1 test in 0.901s

FAILED (errors=1)


I think test_device.py just needs to ignore the exit code from self.device.install(), but I'm not 100% sure. I'll leave it to you guys to fix? Thanks.

Patch-set: 1
Reviewer: Spencer Low <1065256@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0